services:

  # ── Base de datos MySQL 9.7 ───────────────────────────────────────────────────
  db:
    image: mysql:9.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: django_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "django_user", "-pdjango_pass"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ── Aplicación Django ─────────────────────────────────────────────────────────
  web:
    build: .
    container_name: django_app
    restart: always
    ports:
      - "80:80"
    environment:
      DJANGO_SECRET_KEY: "super-secret-key-cambiame-en-produccion"
      DB_NAME: django_db
      DB_USER: django_user
      DB_PASSWORD: django_pass
      DB_HOST: db
      DB_PORT: "3306"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  mysql_data:
